### ISSUE TITLE
Unable to Train Random Forest model

### ISSUE THREAD

**Issue by buswrecker** [Microsoft/r-server-campaign-optimization#1]
Hi all, 

I'm having in invalid object CM_AD1 when training the RandomForest model. 

cheers

![invalidobjectname](https://cloud.githubusercontent.com/assets/717900/20781311/de5d1962-b7bc-11e6-85da-c7c402cfcde3.jpg)

**Comment by sdgilley** [comment]
Should be fixed with Commit 0221e8689c04f94959c676bfa92f55add857cb54
